version: '2'
services:
  mqtt:
    image: eclipse/mosquitto:1.4.8
    ports:
      - "1883:1883"
      - "9001:9001"
    expose:
      - "1883"
      - "9001"
    volumes:
      - ./.docker-data/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
