# Generated by Django 2.2.1 on 2019-05-26 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_r', to='dating.Profile')),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_s', to='dating.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_p', models.BooleanField(default=False)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_a', to='dating.Profile')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_b', to='dating.Profile')),
            ],
        ),
    ]
